import { QuizQuestion } from "../types";

export const quizQuestions: QuizQuestion[] = [
  {
    id: "qz1",
    question: "Which of the following describes the key difference between RAG and Fine-Tuning?",
    options: [
      "RAG shifts the model's physical weights; Fine-Tuning acts like an open-book library prompt reference.",
      "RAG represents an open-book exam where context is queried dynamically; Fine-Tuning modifies internal weight synapses to teach tone or narrow format behavior.",
      "Fine-tuning is zero-cost; RAG demands continuous high GPU supercomputer clusters for retraining weights.",
      "There is no functional or behavioral difference."
    ],
    correctIndex: 1,
    explanation: "RAG is 'open book' and loads context into the prompts on first use without altering foundation model parameters. Fine-tuning is 'study prep' and tweaks the physical weight arrays to master format consistency long term."
  },
  {
    id: "qz2",
    question: "In Model Context Protocol (MCP), what capability is responsible for executable functions?",
    options: [
      "Resources (which read static variables)",
      "Prompts (which define instruction cards)",
      "Tools (which expose executable functions like writing files or querying SQL)",
      "Clients (which compile the model context)"
    ],
    correctIndex: 2,
    explanation: "MCP servers represent three capabilities: Prompts, Resources (read-only documents), and Tools (active operations or function invocations that clients can execute)."
  },
  {
    id: "qz3",
    question: "Why does Low-Rank Adaptation (LoRA) save significant memory during training?",
    options: [
      "It compresses prompts by trimming context tokens.",
      "It freezes original foundation weights and injects tiny, low-rank parameter decomposition matrices into attention projections.",
      "It runs models on local browser frameworks without graphics cards.",
      "It deletes hidden deep multilayer neuron clusters."
    ],
    correctIndex: 1,
    explanation: "LoRA factorizes massive d x k parameter optimizations into two low-rank matrices d x r and r x k (where r is tiny, like 4 or 8), dropping trainable variables by up to 99%."
  },
  {
    id: "qz4",
    question: "Which evaluation metric of the RAG Triad computes whether claims generated by the LLM are backed solely by references in retrieved files?",
    options: [
      "Context Relevance",
      "Answer Relevance",
      "Groundedness / Faithfulness",
      "Cosine Semantic Closeness"
    ],
    correctIndex: 2,
    explanation: "Groundedness (or Faithfulness) measures whether the claims made inside the final generated text are backed up by facts found inside the retrieved knowledge nodes, detecting hallucinations."
  },
  {
    id: "qz5",
    question: "What primary bottleneck in older NLP sequential networks (RNNs) did Self-Attention solve?",
    options: [
      "It increased prompt token prices.",
      "It allowed parallel GPU backpropagation of sequence steps simultaneously instead of sequential word-by-word steps.",
      "It removed multi-head vector indexes entirely.",
      "It forced models to use strict relational databases."
    ],
    correctIndex: 1,
    explanation: "RNN structures process words sequentially one after another, bottlenecking parallel multi-node GPU workflows. Self-Attention scores mathematical relation weights across all word positions at once in O(1) sequential steps."
  },
  {
    id: "qz6",
    question: "What is the primary defining feature of an 'Agentic Loop' compared to a chain of simple prompts?",
    options: [
      "The use of multiple Gemini models synchronously.",
      "Dynamic routing and iterative decision-making where the model runs tools and evaluates outputs in an active feedback loop.",
      "Encoding the prompt strictly in binary schemas.",
      "Having a human write the responses manually inside a terminal."
    ],
    correctIndex: 1,
    explanation: "Traditional chains execute in linear streams without recovery. Agentic loops introduce cognitive checks: the LLM calls a tool, observes results, and autonomously decides whether to refine, finish, or change tracks."
  },
  {
    id: "qz7",
    question: "What mathematical simplification does Direct Preference Optimization (DPO) bring compared to Reinforcement Learning (RLHF)?",
    options: [
      "It uses prompt length to measure quality.",
      "It drops the separate Reward Model and active PPO policy optimization steps, training the policy directly on preference pairs via classification loss.",
      "It replaces self-attention matrices with linear vectors.",
      "It converts text into images before scoring them."
    ],
    correctIndex: 1,
    explanation: "DPO mathematically proves that the optimization problem of RLHF with a reward model can be solved via a closed-form substitution. This allows SFT-style direct tuning of the language model using paired preference datasets."
  },
  {
    id: "qz8",
    question: "What does model quantization (e.g., INT8 or FP4) do to a neural network?",
    options: [
      "It increases context window capacity.",
      "It reduces parameter precision representation to decrease RAM footprint and speed up calculations.",
      "It trains the model on custom database schemas.",
      "It deletes security instructions inside system prompts."
    ],
    correctIndex: 1,
    explanation: "Quantization converts continuous 16-bit float weight representations down to smaller discrete representations (like 8-bit or 4-bit integers), which drastically reduces GPU memory usage and accelerates token speed."
  },
  {
    id: "qz9",
    question: "What happens if you set an LLM's 'Temperature' parameter closer to 0.0 in production?",
    options: [
      "The model will generate highly creative, unpredictable stories.",
      "The model's token distribution collapses around the peak probability, making outputs highly deterministic and logical.",
      "The model's API call cost will double.",
      "The model stops using self-attention layers."
    ],
    correctIndex: 1,
    explanation: "Lowering temperature reduces the random scattering during token sampling, prioritizing high-probability sequences, which leads to highly repeatable, factual, and strict schema-compliant JSON outputs."
  },
  {
    id: "qz10",
    question: "What is the best defense against 'Indirect Prompt Injection' in a RAG pipeline?",
    options: [
      "Never using context retrieval at all.",
      "Treating retrieved context payloads as untrusted user inputs, using defensive XML tag isolation, and running post-generation safety class checks.",
      "Setting temperature to 2.0 to bypass inputs.",
      "Running the database inside a local Docker container."
    ],
    correctIndex: 1,
    explanation: "Because indirect injection occurs when a RAG search fetches adversarial payloads hidden in third-party files, systems must isolate context blocks from core system prompts, and double-check outputs before rendering."
  },
  {
    id: "qz11",
    question: "What is a main advantage of the Hierarchical Navigable Small World (HNSW) vector index?",
    options: [
      "It compresses vectors down to 1% of their size.",
      "It uses multi-layered graph structures to achieve lightning-fast approximate nearest neighbor lookups with high recall.",
      "It does not require RAM to store graph files.",
      "It automatically translates text into five global languages."
    ],
    correctIndex: 1,
    explanation: "HNSW is a highly optimized graph-based index. It creates hierarchical navigation levels where the top level does fast macro-routing and lower levels find precise local neighbors with near-perfect retrieval recall."
  },
  {
    id: "qz12",
    question: "In LLM-as-a-Judge evaluations, how does 'Verbosity Bias' skew scores?",
    options: [
      "Judges rate math formulas lower than stories.",
      "Judges consistently award higher scores to longer, flowery responses even if they lack factual substance.",
      "Judges refuse to grade code written in Python.",
      "Judges score their own brand of models lower."
    ],
    correctIndex: 1,
    explanation: "Advanced LLM judges exhibit verbosity bias, meaning they correlate response length and structure density with output quality, frequently penalizing direct, short, and accurate solutions."
  }
];
